services:
  api:
    build: . #coge todo lo de la ra√≠z
    container_name: api #nombre contenedor.
    restart: always #reiniciar el servicio siempre.
    environment:
      SPRING_PROFILES_ACTIVE: local
    ports:
      - "8081:8080"

  db:
    image: mysql:8.0
    container_name: baseDatos
    environment:
      MYSQL_ROOT_PASSWORD: root
    restart: always
    volumes:
      - ./sql/mysql:/docker-entrypoint-initdb.d #Coge el archivo SQL de la ruta en la que se encuentre.
      - db_data:/var/lib/mysql #Mantiene los datos.
    ports:
      - "3307:3306"

volumes:
  db_data: #Variable para instanciar el volumen.